---
title: Analisi serie di temperatura e precipitazione
date: '`r Sys.Date()`'
author: Guido
affiliation: ISPRA
---

Analisi dei risultati per l'identificazione delle serie di temperatura e precipitazione valide per:

- calcolo dei valori climatologici
- calcolo dei trend di lungo periodo

## Abruzzo

- [precipitazione](./abruzzo/prcp.abruzzo.descrizioneSerie.html)
- [tmax](./abruzzo/tmax.abruzzo.descrizioneSerie.html)
- [tmin](./abruzzo/tmin.abruzzo.descrizioneSerie.html)

## Aeronautica

- [precipitazione](./aeronautica/prcp.aeronautica.descrizioneSerie.html)
- [tmax](./aeronautica/tmax.aeronautica.descrizioneSerie.html)
- [tmin](./aeronautica/tmin.aeronautica.descrizioneSerie.html)

## Basilicata

- [precipitazione](./basilicata/prcp.basilicata.descrizioneSerie.html)
- [tmax](./basilicata/tmax.basilicata.descrizioneSerie.html)
- [tmin](./basilicata/tmin.basilicata.descrizioneSerie.html)

## Bolzano

- [precipitazione](./bolzano/prcp.bolzano.descrizioneSerie.html)
- [tmax](./bolzano/tmax.bolzano.descrizioneSerie.html)
- [tmin](./bolzano/tmin.bolzano.descrizioneSerie.html)

## Calabria

- [precipitazione](./calabria/prcp.calabria.descrizioneSerie.html)
- [tmax](./calabria/tmax.calabria.descrizioneSerie.html)
- [tmin](./calabria/tmin.calabria.descrizioneSerie.html)

## Campania

- [precipitazione](./campania/prcp.campania.descrizioneSerie.html)
- [tmax](./campania/tmax.campania.descrizioneSerie.html)
- [tmin](./campania/tmin.campania.descrizioneSerie.html)

### Emilia Romagna

- [precipitazione](./emiliaromagna/prcp.emiliaromagna.descrizioneSerie.html)
- [tmax](./emiliaromagna/tmax.emiliaromagna.descrizioneSerie.html)
- [tmin](./emiliaromagna/tmin.emiliaromagna.descrizioneSerie.html)

### Friuli Venezia Giulia

- [precipitazione](./friuliveneziagiulia/prcp.friuliveneziagiulia.descrizioneSerie.html)
- [tmax](./friuliveneziagiulia/tmax.friuliveneziagiulia.descrizioneSerie.html)
- [tmin](./friuliveneziagiulia/tmin.friuliveneziagiulia.descrizioneSerie.html)

### Lazio

- [precipitazione](./lazio/prcp.lazio.descrizioneSerie.html)
- [tmax](./lazio/tmax.lazio.descrizioneSerie.html)
- [tmin](./lazio/tmin.lazio.descrizioneSerie.html)

### Liguria

- [precipitazione](./liguria/prcp.liguria.descrizioneSerie.html)
- [tmax](./liguria/tmax.liguria.descrizioneSerie.html)
- [tmin](./liguria/tmin.liguria.descrizioneSerie.html)

### Lombardia

- [precipitazione](./lombardia/prcp.lombardia.descrizioneSerie.html)
- [tmax](./lombardia/tmax.lombardia.descrizioneSerie.html)
- [tmin](./lombardia/tmin.lombardia.descrizioneSerie.html)

### Marche

- [precipitazione](./marche/prcp.marche.descrizioneSerie.html)
- [tmax](./marche/tmax.marche.descrizioneSerie.html)
- [tmin](./marche/tmin.marche.descrizioneSerie.html)


### Piemonte

- [precipitazione](./piemonte/prcp.piemonte.descrizioneSerie.html)
- [tmax](./piemonte/tmax.piemonte.descrizioneSerie.html)
- [tmin](./piemonte/tmin.piemonte.descrizioneSerie.html)

### Puglia

- [precipitazione](./puglia/prcp.puglia.descrizioneSerie.html)
- [tmax](./puglia/tmax.puglia.descrizioneSerie.html)
- [tmin](./puglia/tmin.puglia.descrizioneSerie.html)


### Sardegna

- [precipitazione](./sardegna/prcp.sardegna.descrizioneSerie.html)
- [tmax](./sardegna/tmax.sardegna.descrizioneSerie.html)
- [tmin](./sardegna/tmin.sardegna.descrizioneSerie.html)


### Sicilia

- [precipitazione](./sicilia/prcp.sicilia.descrizioneSerie.html)
- [tmax](./sicilia/tmax.sicilia.descrizioneSerie.html)
- [tmin](./sicilia/tmin.sicilia.descrizioneSerie.html)

### Toscana

- [precipitazione](./toscana/prcp.toscana.descrizioneSerie.html)
- [tmax](./toscana/tmax.toscana.descrizioneSerie.html)
- [tmin](./toscana/tmin.toscana.descrizioneSerie.html)

### Trentino

- [precipitazione](./trentino/prcp.trentino.descrizioneSerie.html)
- [tmax](./trentino/tmax.trentino.descrizioneSerie.html)
- [tmin](./trentino/tmin.trentino.descrizioneSerie.html)

### Valle d'Aosta

- [precipitazione](./valledaosta/prcp.valledaosta.descrizioneSerie.html)
- [tmax](./valledaosta/tmax.valledaosta.descrizioneSerie.html)
- [tmin](./valledaosta/tmin.valledaosta.descrizioneSerie.html)

### Umbria

- [precipitazione](./umbria/prcp.umbria.descrizioneSerie.html)
- [tmax](./umbria/tmax.umbria.descrizioneSerie.html)
- [tmin](./umbria/tmin.umbria.descrizioneSerie.html)

### Veneto

- [precipitazione](./veneto/prcp.veneto.descrizioneSerie.html)
- [tmax](./veneto/tmax.veneto.descrizioneSerie.html)
- [tmin](./veneto/tmin.veneto.descrizioneSerie.html)

